# Generated by Django 3.2.12 on 2023-03-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('subjectcode', models.CharField(default='', max_length=50)),
                ('marks', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
