# Generated by Django 3.2.12 on 2023-03-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_marksmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents')),
                ('subjectcode', models.CharField(default='', max_length=50)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
